django_db/urls.py
from django.contrib import admin
from django.urls import path
from query.views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',index),
    path('query_patient/',query_patient),
    path('query_detail/',query_detail),
    path('query_adetail/',query_adetail),
    path('main/',mainpage),
    path('patient_add/',patient_add),
    path('logout/',logout_d),
    path('get_patient/',get_patient),
    path('del_patient/',del_patient),
    path('detail_add/',detail_add),
    path('adetail_add/',adetail_add),
    path('get_detail/',get_detail),
    path('get_adetail/',get_adetail),
    path('detail_del/',detail_del),
    path('adetail_del/',adetail_del),
    path('get_hos/',get_hos),
    path('get_doc/',get_doc),
    path('getUser/',getuser),
    path('edit_user/',edituser),
    path('edit_pass/',editpass),
    path('get_info/',getinfo),
    path('chart/',chart),
    path('get_chart/',get_chart),
    path("get_users/",get_users),
    path("l_change/",ex_level),
    path("delu/",delu),
]

query/views.py
from django.shortcuts import render
from . import models
from django.db.models import *
import json
from django.http import HttpResponse,HttpResponseRedirect, request
from django.views.decorators.csrf import csrf_exempt
from datetime import datetime
from django.contrib.auth import login,authenticate,logout
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required

# Create your views here.
@csrf_exempt
def index(request):
    next = request.GET.get('next', '/')
    if request.method=='POST':
        obj = request.POST
        st = obj.get("st")
        if st=='l':
            user = obj.get("user")
            if user==None:
                return render(request,'query/index.html',{"obj":obj,"st":"l"})
            pwd = obj.get("pwd")
            logininfo = authenticate(username=user, password=pwd)
            if logininfo != None:
                login(request,logininfo)
                data = {"tip":"登录成功，正在跳转...","class":"success","url":next}
                return HttpResponse(json.dumps(data))
            else:
                data = {"tip":"用户名或密码错误！","class":"danger"}
                return HttpResponse(json.dumps(data))
            #print(request.user.is_authenticated)
        else:
            user = obj.get("user")
            if user==None:
                return render(request,'query/index.html',{"obj":obj,"st":"r"})
            pwd = obj.get("pwd")
            sex = obj.get("sex")
            age = obj.get("age")
            name = obj.get("name")
            dep = obj.get("dep")
            hos = obj.get("hos")

            hosid = models.HospitalRecord.objects.filter(institutename=hos)
            state = models.User.objects.filter(userid__exact=user)
            if len(state)!=0:
                data = {"tip":"用户名重复，请重试！","class":"danger"}
                return HttpResponse(json.dumps(data))
            elif len(hosid)==0:
                data = {"tip":"医院未涵盖，请重试！","class":"danger"}
                return HttpResponse(json.dumps(data))
            else:
                models.User.objects.create(userid=user,age=age,departmentid=dep,username=name,gender=sex,hospitalid=hosid[0].instituteid)
                User.objects.create_user(username=user, password=pwd,first_name=name)
                data = {"tip":"注册成功,请登录!","class":"success"}
                return HttpResponse(json.dumps(data))
    else:
        if request.user.is_authenticated:
            return HttpResponseRedirect("/main/")
        if next != '/':
            return render(request,'query/index.html',{"st":"l","error":"请先登录！"})
        return render(request,'query/index.html')        

def logout_d(request):
    logout(request)
    return HttpResponseRedirect("/")

@login_required
@csrf_exempt
def chart(request):
    if request.method == "GET":
        return render(request,"query/chart.html")

@login_required
@csrf_exempt
def get_chart(request):
    if request.method == "POST":
        agey = models.Patientbasicinfos.objects.values("age").annotate(Count=Count('age')).order_by("age")
        aa = {i["age"]:i["Count"] for i in agey}
        xd = [i for i in range(agey.last()['age'])]
        yd = [0]
        for i in xd:
            if i in aa.keys():
                yd.append(aa[i])
            else:
                yd.append(0)
        yd[1]=0
        age = {"xdata":xd,"ydata":yd}

        sexy = [i['Count'] for i in models.Patientbasicinfos.objects.values("gender").annotate(Count=Count('gender')).order_by("gender")]
        sex = {"xdata":["女性","男性"],"ydata":sexy}   

        disy = models.DArearoi.objects.values("diseaseid").annotate(Count=Count('diseaseid')).order_by("diseaseid")
        dis = [{'name':models.Diseasedict.objects.get(diseaseid=i['diseaseid']).diseasename,"value":i['Count']} for i in disy]  

        areay = models.AArearoi.objects.values("anatomyid").annotate(Count=Count('anatomyid')).order_by("anatomyid")
        area = [{"name":models.Anatomydict.objects.get(anatomyid=i['anatomyid']).anatomyname,"value":i['Count']} for i in areay]
        
        data = {"age":age,"sex":sex,"dis":dis,"area":area}
        return HttpResponse(json.dumps(data))

@csrf_exempt
def getinfo(request):
    doc = len(models.User.objects.all())
    hos = len(models.HospitalRecord.objects.all())
    pat = len(models.Patientbasicinfos.objects.all())
    dis = len(models.DLabeledimage.objects.all())
    bz = len(models.ALabeledimage.objects.all())

    data = {"doc":doc,"hos":hos,"pat":pat,"dis":dis,"bz":bz}
    return HttpResponse(json.dumps(data))

@csrf_exempt
@login_required
def get_users(request):
    if request.method == "POST":
        ousers = models.User.objects.all()
        users = []
        for i in ousers:
            hos = models.HospitalRecord.objects.get(instituteid=i.hospitalid).institutename
            info = models.AuthUser.objects.get(username=i.userid)
            level = "站长" if info.is_superuser==1 else "管理员" if info.is_staff==1 else "普通用户"
            users.append({"id":i.userid,"name":i.username,"level":level,"age":i.age,"sex":i.gender,"dep":i.departmentid,"hos":hos})
        
        data = {"users":users}
        return HttpResponse(json.dumps(data))

@csrf_exempt
@login_required
def delu(request):
    if request.method == "POST":
        pid = request.POST.get("id")

        models.User.objects.filter(userid=pid).delete()
        models.AuthUser.objects.filter(username=pid).delete()
        data = {"class":"success"}

        return HttpResponse(json.dumps(data))

@csrf_exempt
@login_required
def ex_level(request):
    if request.method == "POST":
        p = int(request.POST.get("p"))
        pid = request.POST.get("id")

        info = models.AuthUser.objects.get(username=pid)
        if info.is_superuser==1:
            if p==-1:
                isu = 0
                st = p
            else:
                isu = 1
                st = 0
            ist = info.is_staff
        elif info.is_staff==1:
            if p==-1:
                isu = 0
                ist = 0
            else:
                isu = 1
                ist = 1
            st = p
        else:
            isu = 0
            if p==1:
                ist = 1
                st = p
            else:
                ist = 0
                st = 0

        models.AuthUser.objects.filter(username=pid).update(is_staff=ist,is_superuser=isu)
        #print(isu,ist,st)
        data = {"state":st}
        return HttpResponse(json.dumps(data)) 


@csrf_exempt
@login_required
def getuser(request):
    if request.method == "POST":
        userid = request.user
        user = models.User.objects.get(userid=userid)
        hos = models.HospitalRecord.objects.get(instituteid=user.hospitalid).institutename
        level = request.user.is_staff
        supers = request.user.is_superuser
        if supers==1:
            level = 2

        data = {'id':user.userid,"name":user.username,"age":user.age,"gender":user.gender,"hos":hos,"dep":user.departmentid,"level":level}
        return HttpResponse(json.dumps(data))

@csrf_exempt
@login_required
def editpass(request):
    if request.method == "POST":
        old = request.POST.get("old")
        new = request.POST.get("new")

        user = authenticate(username=request.user, password=old)
        if user == None:
            data = {"class":"danger"}
        else:
            user.set_password(new)
            user.save()
            login(request,user)
            data = {"class":"success"}
        
        return HttpResponse(json.dumps(data))
        

@csrf_exempt
@login_required
def edituser(request):
    if request.method == "POST":
        obj = request.POST
        name = obj.get("name")
        sex = obj.get("sex")
        age = obj.get("age")
        hos = obj.get("hos")
        dep = obj.get("dep")

        hosid = models.HospitalRecord.objects.get(institutename=hos).instituteid
        models.AuthUser.objects.filter(username=request.user).update(first_name=name)
        models.User.objects.filter(userid=request.user).update(username=name,gender=sex,age=age,hospitalid=hosid,departmentid=dep)
        data = {"class":"success"}
        return HttpResponse(json.dumps(data))

@login_required
def mainpage(request):
    #userid = request.user
    #user = userid.first_name
    #print(type(userid),user)
    return render(request,'query/main.html')

@csrf_exempt
def get_hos(request):
    if request.method=="POST":
        hos = models.HospitalRecord.objects.all()
        data = [i.institutename for i in hos]
        return HttpResponse(json.dumps(data))

@csrf_exempt
@login_required
def get_doc(request):
    if request.method=="POST":
        doctor = models.User.objects.all()
        data = [i.username for i in doctor]
        return HttpResponse(json.dumps(data))

@csrf_exempt
@login_required
def get_patient(request):
    if request.method=='POST':
        pid = request.POST.get("pid")
        patient = models.Patientbasicinfos.objects.get(id=pid)
        hos = models.HospitalRecord.objects.get(instituteid=patient.hospitalid).institutename
        checkdate = datetime.strftime(patient.checkdate,"%Y-%m-%d")
        data = {"name":patient.patientname,"sex":patient.gender,"age":patient.age,"hos":hos,"checkdate":checkdate,\
            "checkid":patient.checknumber,"pid":patient.patientid,"id":patient.id}
        return HttpResponse(json.dumps(data))

@csrf_exempt
@login_required
def get_detail(request):
    if request.method=='POST':
        pid = request.POST.get("pid")
        bz = models.DLabeledimage.objects.get(id=pid)
        da = [i.diseaseid for i in models.DArearoi.objects.filter(areaid=bz.areaid)]
        datype = ','.join([i.diseasename for i in models.Diseasedict.objects.filter(diseaseid__in=da)])
        ppid = models.Patientbasicinfos.objects.get(patientid=bz.patientid).id
        doctor = models.User.objects.get(userid=bz.userid).username

query/templates/query/detail.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="/static/plugins/bootstrap-3.4.1-dist/css/bootstrap.css">
    <link rel="icon" href="/static/img/favicon.ico">
    <title>{{ title }}标注查询</title>
    <link rel="stylesheet" href="/static/plugins/bootstrap-3.4.1-dist/css/mycss.css">
</head>
<body style="padding-top: 70px;padding-bottom: 70px">
    <script type="text/javascript" src="/static/plugins/bootstrap-3.4.1-dist/js/jquery-3.6.0.min.js"></script>
    <script type="text/javascript" src="/static/plugins/bootstrap-3.4.1-dist/js/bootstrap.js"></script>
<nav class="navbar navbar-inverse navbar-fixed-top ">
    <div class="container navbar-left" style="width: 40%;">
        <div class="navbar-header">
            <a class="navbar-brand" style="color: azure;" href="/main/">医疗管理系统</a>
            <!--<p class="navbar-text">患者信息查询</p>-->
        </div>
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li><a href="/main/">主页</a></li>
                <li><a href="/query_patient/">患者信息</a></li>
                <li class="dropdown active">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">标注记录 <span class="caret"></span></a>
                <ul class="dropdown-menu">
                    <li><a href="/query_detail/">疾病标注</a></li>
                    <li><a href="/query_adetail/">解剖标注</a></li>
                </ul>
                </li>
                <li><a href="/chart/">统计图表</a></li>
            </ul>
        </div>
    </div>
    <div class="container navbar-right" style="width: 20%;margin-right: 20px;">
        <div class="collapse navbar-collapse">
            <ul class="nav navbar-nav navbar-right">
                <li style="margin-right: 20px;"><p class="lip">{{request.user.first_name}},欢迎您</p></li>
                <li><a href="/logout/">退出</a></li>
            </ul>
        </div>
    </div>
</nav>
<nav class="navbar navbar-inverse navbar-fixed-bottom ">
    <div class="container navbar-left" style="width: 45%;">
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li style="margin-right: 20px;"><p class="lip"><em>Powered By</em></p></li>
                <li><a href="https://www.djangoproject.com/">Django</a></li>
                <li><a href="https://v3.bootcss.com/">Bootstrap V3</Var></a></li>
            </ul>
        </div>
    </div>
    <div class="container navbar-left" style="width: 15%;">
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-2">
            <ul class="nav navbar-nav">
                <li><p class="lip">2021 Created by Jimmy</p></li>
            </ul>
        </div>
    </div>
    <div class="container navbar-right" style="width: 25%;margin-right: 20px;">
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-3">
            <ul class="nav navbar-nav navbar-right">
                <li><a data-container="body" data-toggle="popover" data-placement="left" data-content="嘿嘿，交出你的联系方式！" href="#">联系我</a></li>
            </ul>
        </div>
    </div>
</nav>

{% if error%}
<div class="alert alert-danger" style="margin:0.5% 1.5% 1% 1.5%;" role="alert"> 
    <p>{{error}}</p>
</div> 
{% endif%}



<div class="container-fluid">
    
    <div class="panel panel-default" style="width: 500px;height: 360px;margin: 0px auto;">
        <div class="panel-heading" style="text-align: center;"><h3 class="panel-title">{{ title }}标注条件筛选</h3></div>
        <div class="panel-body" style="text-align: center;">
            <p class="lead" id="ptname">未指定患者</p>
        <form id="query" class="form-horizontal">
        <div class="form-group">
            <label class="col-sm-4 control-label" for="id_patient">病人ID</label>
            <input class="form-control" style="width: 200px;" type="text" id="id_patient" name="pid" placeholder="请输入病人ID">
        </div>
        <div class="form-group">
            <label class="col-sm-4 control-label" for="doctor">标注医生</label>
            <select class="form-control doctorq" style="width: 200px;" id="doctor_name" name='doctor'>
                <option value="">全部</option>
            </select>
        </div>
        <div class="form-group">
            <label class="col-sm-4 control-label" for="illness_type">{{ title }}类型</label>
            <input type="text" class="form-control" style="width: 200px;" id="illness_type" name="da_type" placeholder="请输入{{title}}类型">
        </div>
        <div class="form-group">
            <label class="col-sm-4 control-label" for="type">标注类型</label>
            <select class="form-control" style="width: 200px;" type="text" id="type" name='bztype'>
                <option value="">全部</option>
                <option value="RECTANGLE">Rectangle</option>
                <option value="POLYGON">Polygon</option>
                <option value="HAND">Hand</option>
            </select>
        </div>
        <button class="btn btn-info" type="button" style="margin-top: 5px;" data-toggle="modal" data-target="#addbz" onclick="$('#name_add').val($('#id_patient').val());">
            <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span> 新增
        </button>
        <button id="bquery" class="btn btn-primary" style="margin-top: 5px;margin-left: 10px;" type="submit">
            <span class="glyphicon glyphicon-search" aria-hidden="true"></span> 查询
        </button>
    </form>
    </div>
    </div>
</div>

<div class="modal fade" id="addbz" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
      <div class="modal-content" style="width: 800px;">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <h4 class="modal-title" id="addpa_t">新增{{title}}标注</h4>
        </div>
        <div class="modal-body" style="text-align: center;">
            <form id="add_form" name="add_form" method="POST" class="form-horizontal">
                <div class="container-fluid">
                    <div class="col-md-6">
                        <div class="form-group">
                            <label for="name_add" class="col-sm-4 control-label">患者&nbsp;&nbsp;&nbsp;ID：</label>
                            <input class="form-control" type="text" id="name_add" name="name" placeholder="请输入患者ID" style="width: 220px;" required>
                        </div>
                        <div class="form-group">
                            <label for="sex_add" class="col-sm-4 control-label">标注医生：</label>
                            <select class="form-control doctor" id="doctor_add" name="doctor" style="width: 220px;">
                            </select>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-4 control-label">{{title}}类型：</label>
                            <input type="text" id="id_add" name="type" class="form-control" placeholder="多个请以,分开" style="width: 220px;" required>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <label class="col-sm-4 control-label">标注类型：</label>
                            <select class="form-control" id="bztype_add" name="bztype" style="width: 220px;">
                                <option value="RECTANGLE">Rectangle</option>
                                <option value="POLYGON">Polygon</option>
                                <option value="HAND">Hand</option>
                            </select>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-4 control-label">图像&nbsp;&nbsp;&nbsp;ID：</label>
                            <input type="text" class="form-control" id="imageid_add" name="imageid" placeholder="请输入图像ID" style="width: 220px;" required>
                        </div>
                        <div class="form-group">
                            <label for="age_add" class="col-sm-4 control-label">区域编号：</label>
                            <input type="text" class="form-control" id="area_add" name="areaid" placeholder="请输入区域编号" style="width: 220px;" required>
                        </div>
                    </div>
                </div>
            </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">关闭</button>
          <button type="submit" class="btn btn-primary" id="add_sub">确认</button> 
        </div>
    </form>
      </div>
    </div>
</div>

<div class="modal fade" id="editbz" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
      <div class="modal-content" style="width: 800px;">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <h4 class="modal-title" id="editpa_t">修改{{title}}标注</h4>
        </div>
        <div class="modal-body" style="text-align: center;">
            <form id="edit_form" name="edit_form" method="POST" class="form-horizontal">
                <div class="container-fluid">
                    <div class="col-md-6">
                        <div class="form-group">
                            <label for="name_edit" class="col-sm-4 control-label">患者&nbsp;&nbsp;&nbsp;ID：</label>
                            <input class="form-control" type="text" id="name_edit" name="name" placeholder="请输入患者ID" style="width: 220px;" required>
                        </div>
                        <div class="form-group">
                            <label for="sex_edit" class="col-sm-4 control-label">标注医生：</label>
                            <select class="form-control doctor" id="doctor_edit" name="doctor" style="width: 220px;">
                            </select>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-4 control-label">{{title}}类型：</label>
                            <input type="text" id="id_add" name="type" class="form-control" placeholder="多个请以,分开" style="width: 220px;" required>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <label class="col-sm-4 control-label">标注类型：</label>
                            <select class="form-control" id="bztype_edit" name="bztype" style="width: 220px;">
                                <option value="RECTANGLE">Rectangle</option>
                                <option value="POLYGON">Polygon</option>
                                <option value="HAND">Hand</option>
                            </select>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-4 control-label">图像&nbsp;&nbsp;&nbsp;ID：</label>
                            <input type="text" class="form-control" id="imageid_edit" name="imageid" placeholder="请输入图像ID" style="width: 220px;" readonly>
                        </div>
                        <div class="form-group">
                            <label for="age_edit" class="col-sm-4 control-label">区域编号：</label>
                            <input type="text" class="form-control" id="area_edit" name="areaid" placeholder="请输入区域编号" style="width: 220px;" readonly>
                        </div>
                    </div>
                </div>
            </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">关闭</button>
          <button type="submit" class="btn btn-primary" id="edit_sub">更新</button> 
        </div>
    </form>
      </div>
    </div>
</div>

<div id="tip" class="alert alert-success" style="margin:1% 1.5% 1% 1.5%;text-align: center;" role="alert" hidden>  
    <p id="tip_c"></p>
</div> 

<div id="tip2" class="alert alert-success" style="margin:1% 1.5% 1%;text-align: center;" role="alert" hidden>  
    <p id="tip_c2"></p>
</div> 

<div style="margin-left:1.5%;margin-right: 1.5%;text-align: center;" id="result" hidden>
    <nav aria-label="Page navigation">
        <ul class="pagination">
          <li>
            <a href="javascript:$.nextpage(-1)" aria-label="Previous">
              <span aria-hidden="true">&laquo;</span>
            </a>
          </li>
        </ul>
      </nav>
<div style="margin-left:1.5%;margin-right: 1.5%;">
<table class="table table-hover" id="retable" border="2">
    <tr style="background-color: lightgrey;">
        <td></td>
        <td><strong>标注ID</strong></td>
        <td><strong>图像ID</strong></td>
        <td><strong>标注类型</strong></td>
        <td><strong>标注医生</strong></td>
        <td><strong>患者ID</strong></td>
        <td><strong>患者姓名</strong></td>
        <td><strong>{{title}}类型</strong></td>
        <td><strong>区域编号</strong></td>
        <td><strong>图像路径</strong></td>
    </tr>  
</table>
</div>
<script type="text/javascript" src="/static/js/detail.js"></script>

<script>
    var page=1
    var pnow=1
    var type="{{type}}"

    $.init =function(){
        $("#id_patient").val('{{obj.id}}')
        $("#doctor_name").val('{{obj.doctor}}') 
        $("#illness_type").val('{{obj.type}}')
        //console.log($("#doctor_name").html())
        {% if obj.ptype %}
        $("#type").val('{{obj.ptype}}')
        {% endif %}
        {% if obj.ptype or obj.id or obj.doctor or obj.type %}
        $.getContent()
        {% endif %}
    }
$.init()
</script>
</body>
</html>

query/templates/query/index.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <link rel="icon" href="/static/img/favicon.ico">
    <link rel="stylesheet" href="/static/plugins/bootstrap-3.4.1-dist/css/bootstrap.css">
    <title>医疗管理系统</title>
</head>
<body style="padding-top: 70px;padding-bottom: 70px">
    <script type="text/javascript" src="/static/plugins/bootstrap-3.4.1-dist/js/jquery-3.6.0.min.js"></script>
    <script type="text/javascript" src="/static/plugins/bootstrap-3.4.1-dist/js/bootstrap.js"></script>
<nav class="navbar navbar-inverse navbar-fixed-top ">
    <div class="container navbar-left" style="width: 30%;">
        <div class="navbar-header">
            <a class="navbar-brand" style="color: azure;" href="">医疗管理系统</a>
        </div>
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li class="active" id="blog"><a href="javascript:$.tologin()">登录</a></li>
                <li id="breg"><a href="javascript:$.toreg()">注册</a></li>
            </ul>
        </div>
    </div>
</nav>
<nav class="navbar navbar-inverse navbar-fixed-bottom ">
    <div class="container navbar-left" style="width: 45%;">
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li><a href="#"><em>Powered By</em></a></li>
                <li><a href="https://www.djangoproject.com/">Django</a></li>
                <li><a href="https://v3.bootcss.com/">Bootstrap V3</Var></a></li>
            </ul>
        </div>
    </div>
    <div class="container navbar-left" style="width: 15%;">
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-2">
            <ul class="nav navbar-nav">
                <li><a href="#">2021 Created by Jimmy</a></li>
            </ul>
        </div>
    </div>
    <div class="container navbar-right" style="width: 8%;">
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-3">
            <ul class="nav navbar-nav">
                <li><a data-container="body" data-toggle="popover" data-placement="left" data-content="嘿嘿，交出你的联系方式！" href="#">联系我</a></li>
            </ul>
        </div>
    </div>
</nav>
<div class="alert alert-success" style="margin:0 auto;text-align: center;width: 430px;" role="alert" id="tip" hidden>  
        <p id="tip_c"></p>
    </div> 


<div class="container-fluid" style="margin-top:50px;">
    <div class="panel panel-default register" style="width: 420px;height: 650px;margin:0 auto;" hidden>
        <div class="panel-heading">注册</div>
        <div class="panel-body register" style="text-align: center;margin-top: 5%;" hidden>
            <form class="form-horizontal" id="regp">
                <div class="form-group">
                    <label class="col-sm-4 control-label">用户名：</label>
                    <input class="form-control" type="text" name="user" style="width: 200px;"  placeholder="输入用户名" required>
                </div><br>
                <div class="form-group">
                    <label  class="col-sm-4 control-label">密&nbsp&nbsp&nbsp&nbsp码：</label>
                    <input class="form-control" type="password" name="pwd" style="width: 200px;"  placeholder="输入密码" required>
                </div> <br>
                <div class="form-group">
                    <label  class="col-sm-4 control-label" for="name">名&nbsp&nbsp&nbsp&nbsp字：</label>
                    <input class="form-control" type="text" id="name" name="name" style="width: 200px;" placeholder="输入你的名字" required>
                </div> <br>
                <div class="form-group">
                    <label class="col-sm-4 control-label">性&nbsp&nbsp&nbsp&nbsp别：</label>
                    <select class="form-control" id="sex" name="sex" style="width: 200px">
                        <option>男</option>
                        <option>女</option>
                    </select>
                </div><br>
                <div class="form-group">
                    <label for="age" class="col-sm-4 control-label">年&nbsp&nbsp&nbsp&nbsp龄：</label>
                    <input class="form-control" type="number" id="age" name="age" min=0 max=120 placeholder="您的年龄" style="width: 200px;" required>
                </div> <br>
                <div class="form-group">
                    <label for="hos" class="col-sm-4 control-label">医&nbsp&nbsp&nbsp&nbsp院：</label>
                    <select class="form-control hospital" style="width: 200px;" id="hos" name="hos" required>
                        <option value="">请选择所在医院</option>
                    </select>
                </div><br>
                <div class="form-group">
                    <label for="pwd" class="col-sm-4 control-label">科&nbsp&nbsp&nbsp&nbsp室：</label>
                    <input class="form-control" style="width: 200px;" type="text" id="dep" name="dep" placeholder="输入所在科室" required>
                </div>    <br>
                <br>
                <input type="hidden" value="r" name="st">
                <button type="submit" class="btn btn-primary" style="width: 60%;">注册</button>
            </form>
        </div>
    </div>

    <div class="panel panel-default login" style="width: 420px;height: 320px;margin:0 auto;">
        <div class="panel-heading">登录</div>
        <div class="panel-body login" style="text-align: center;margin-top: 10%;">
            <form class="form-horizontal" id="logp">
                <div class="form-group">
                    <label for="user" class="col-sm-4 control-label">用户名：</label>
                    <input type="text" class="form-control" id="user" name="user" style="width: 200px;" placeholder="输入用户名" required>
                </div><br>
                <div class="form-group">
                    <label for="pwd" class="col-sm-4 control-label">密&nbsp&nbsp&nbsp&nbsp码：</label>
                    <input type="password" class="form-control" id="pwd" name="pwd" style="width: 200px;" placeholder="输入密码" required>
                </div>    <br><br>
                <input type="hidden" value="l" name="st">
                <button type="submit" class="btn btn-primary" style="width: 60%;">登录</button>
            </form>
        </div>
    </div>
</div>

<script type="text/javascript" src="/static/js/index.js"></script>
</body>
</html>